export const RECEIVE_PATIENTS = 'RECEIVE_PATIENTS'
export const RECEIVE_WOUNDS = 'RECEIVE_WOUNDS'
export const UPDATE_WOUND = 'UPDATE_WOUND'
export const RECEIVE_PATIENT_DETAILS = 'RECEIVE_PATIENT_DETAILS'
